query profile {
  me {
    id
    first_name
    last_name
    avatar
    creation_date
    email
    phone
    role  
    children {
      id
    }
    group {
      id
      name
      children {
        id
        firstName
        lastName
        picture
      }
    }
  }
}
