FROM node:24.11-alpine3.23

WORKDIR /app
RUN apk add --no-cache curl ca-certificates

COPY package*.json ./

RUN npm ci

COPY src ./src
COPY public ./public
COPY next.config.ts ./
COPY postcss.config.mjs ./
COPY tsconfig.json ./

COPY . .
RUN npm run build

CMD ["npm", "run", "start"]